server :
  port : 8080
  error :
    include-message : always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: ap-south-1
  s3:
    buckets:
      customer: sb-practice



spring :
  datasource :
    url : jdbc:postgresql://localhost:5432/customers
    username : postgres
    password : Naaperusiddhu@745
  jpa :
    hibernate :
      ddl-auto :  validate
    properties :
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
    show-sql : true

  main :
    web-application-type : servlet